default:
  tags:
    - docker
    - ubuntu

  image: "nexus.nic.etu:8181/nic/fedora_33:base"

stages:
  - test

test:
  stage: test
  script:
    - dnf update -y  &&  dnf install -y gcc-c++ cmake gtest-devel
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
